downloader-replies:
 build: ./downloader-replies
 volumes:
   - ./downloader-replies:/opt
   - ./libs:/opt/libs
 command: python -u /opt/algoritmoBusqueda.py
 links:
   - downloader-mongo
 restart: always


downloader-streaming:
 build: ./downloader-streaming
 volumes:
   - ./downloader-streaming:/opt
   - ./libs:/opt/libs
 command: python -u /opt/twitterStream.py
 links:
   - downloader-mongo
 restart: always
 

downloader-mongo:
  image: tutum/mongodb:3.2
  environment:
    - AUTH="no"
